# Generated by Django 6.1 on 2026-08-24 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('departamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cnh', models.CharField(max_length=20, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('leve', 'Leve (Até 4 passageiros)'), ('coletivo', 'Coletivo (Até 18 passageiros)')], max_length=20)),
                ('capacidade_maxima', models.IntegerField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=100)),
                ('atividade', models.CharField(max_length=150)),
                ('origem', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=150)),
                ('data', models.DateField()),
                ('horario_saida', models.TimeField()),
                ('horario_retorno', models.TimeField()),
                ('quantidade_passageiros', models.IntegerField()),
                ('status', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='confirmada', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('protocolo_unico', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.motorista')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.colaborador')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.veiculo')),
            ],
        ),
    ]
